Repository sufst/vcu-gui, pull requests merged in 2022-10, with the labels that each got.

#88 chore: clean up for next development cycle
  .gitignore
  .vscode/c_cpp_properties.json
  src/ConfigurationValueTree.cpp
  src/ConfigurationValueTree.h
  src/gui/components/MainComponent.cpp
  src/gui/components/MainComponent.h
Labels: chore

#95 docs: add information on setting up dev environment on Mac / Linux
  docs/Dev Setup.md
Labels: documentation

#98 docs: add information on setting up dev environment on Windows
  README.md
  docs/Dev Setup.md
Labels: documentation

#103 chore: remove driver profiles from old app version
  profiles/Default Linear Profile.xml
  profiles/Torque Limited Profile.xml
Labels: chore

#102 feat(gui): create tab bar
  .trunk/trunk.yaml
  src/gui/CMakeLists.txt
  src/gui/appearance/LookAndFeel.cpp
  src/gui/appearance/LookAndFeel.h
  src/gui/components/InverterConfigComponent.cpp
  src/gui/components/InverterConfigComponent.h
  src/gui/components/MainComponent.cpp
  src/gui/components/MainComponent.h
  src/gui/components/TabbedComponent.cpp
  src/gui/components/TabbedComponent.h
Labels: feature

#104 build(windows): fix missing definition of `M_PI`
  .trunk/config/.clang-format
  src/Interpolator.h
Labels: bug, build

#106 chore: update formatting
  .trunk/config/.clang-format
  .trunk/trunk.yaml
  src/Application.cpp
  src/ConfigurationValueTree.cpp
  src/ConfigurationValueTree.h
  src/Interpolator.h
  src/gui/appearance/LookAndFeel.cpp
  src/gui/appearance/LookAndFeel.h
  src/gui/components/GraphComponent.h
  src/gui/components/InverterConfigComponent.cpp
  src/gui/components/InverterConfigComponent.h
  src/gui/components/MainComponent.cpp
  src/gui/components/MainComponent.h
  src/gui/components/TabbedComponent.cpp
  src/gui/components/TorqueMapComponent.cpp
  src/gui/components/TorqueMapComponent.h
  src/gui/menubar/MenuBar.cpp
  src/gui/menubar/MenuBar.h
  src/gui/utility/PointComparator.h
  src/gui/windows/AboutWindow.cpp
  src/gui/windows/AboutWindow.h
  src/gui/windows/MainWindow.cpp
  src/gui/windows/MainWindow.h
  src/utility/linspace.h
Labels: documentation, chore

#107 docs: update documentation in code
  src/Application.cpp
  src/Application.h
  src/CommandManager.h
  src/ConfigurationValueTree.cpp
  src/ConfigurationValueTree.h
  src/Interpolator.h
  src/Main.cpp
  src/gui/appearance/LookAndFeel.cpp
  src/gui/appearance/LookAndFeel.h
  src/gui/components/GraphComponent.h
  src/gui/components/InverterConfigComponent.cpp
  src/gui/components/InverterConfigComponent.h
  src/gui/components/MainComponent.cpp
  src/gui/components/MainComponent.h
  src/gui/components/TabbedComponent.cpp
  src/gui/components/TabbedComponent.h
  src/gui/components/TorqueMapComponent.cpp
  src/gui/components/TorqueMapComponent.h
  src/gui/menubar/MenuBar.cpp
  src/gui/menubar/MenuBar.h
  src/gui/windows/AboutWindow.cpp
  src/gui/windows/AboutWindow.h
  src/gui/windows/MainWindow.cpp
  src/gui/windows/MainWindow.h
Labels: documentation

#113 feat(gui): create outline for tabs to be added
  src/gui/CMakeLists.txt
  src/gui/components/MainComponent.cpp
  src/gui/components/MainComponent.h
  src/gui/components/config/ConfigEditorComponent.h
  src/gui/components/config/GraphComponent.h
  src/gui/components/config/InverterConfigComponent.cpp
  src/gui/components/config/InverterConfigComponent.h
  src/gui/components/config/TorqueMapComponent.cpp
  src/gui/components/config/TorqueMapComponent.h
Labels: feature

#114 feat(gui): add config load/save to menu bar
  src/CommandManager.h
  src/gui/menubar/MenuBar.cpp
  src/gui/menubar/MenuBar.h
  src/gui/windows/MainWindow.cpp
  src/gui/windows/MainWindow.h
Labels: feature

#116 chore(vscode): add recommended extensions
  .gitignore
  .vscode/extensions.json
Labels: chore

#118 refactor: move utility functions and classes into one place
  src/Interpolator.h
  src/gui/components/config/GraphComponent.h
  src/gui/components/config/TorqueMapComponent.cpp
  src/utility/PointComparator.h
  src/utility/clip.h
  src/utility/linspace.h
Labels: refactor

#122 refactor(gui): simplify menu bar creation
  src/gui/menubar/MenuBar.cpp
  src/gui/menubar/MenuBar.h
Labels: refactor

#121 build(windows): add global _USE_MATH_DEFINE to root CMakeLists
  CMakeLists.txt
  src/Interpolator.h
Labels: build

#123 refactor(utils): move Interpolator into utility folder
  src/ConfigurationValueTree.cpp
  src/gui/components/MainComponent.cpp
  src/gui/components/config/GraphComponent.h
  src/utility/Interpolator.h
Labels: refactor

#105 build(windows): fix issue with GCC specific pragmas
  src/utility/Interpolator.h
Labels: bug, build

#125 feat(config): new data model
  .vscode/launch.json
  CMakeLists.txt
  src/Application.cpp
  src/Application.h
  src/config/CMakeLists.txt
  src/config/ConfigurationValueTree.cpp
  src/config/ConfigurationValueTree.h
  src/config/Constrainers.h
  src/config/Identifiers.h
  src/config/TorqueMap.cpp
  src/config/TorqueMap.h
  src/config/ValueTreeObjectList.h
  src/gui/components/config/InverterConfigComponent.h
  src/gui/components/config/TorqueMapComponent.h
  src/gui/windows/MainWindow.h
Labels: feature

#131 chore(vscode): add build configs for linux
  .vscode/c_cpp_properties.json
  .vscode/launch.json
Labels: build, chore

#132 feat(config)!: create new data model for config
  .vscode/launch.json
  CMakeLists.txt
  src/Application.cpp
  src/Application.h
  src/ConfigurationValueTree.cpp
  src/ConfigurationValueTree.h
  src/config/CMakeLists.txt
  src/config/Constrainers.h
  src/config/DataModel.cpp
  src/config/DataModel.h
  src/config/Identifiers.h
  src/config/Metadata.cpp
  src/config/Metadata.h
  src/config/TorqueMap.cpp
  src/config/TorqueMap.h
  src/config/ValueTreeObjectList.h
  src/gui/CMakeLists.txt
  src/gui/components/MainComponent.cpp
  src/gui/components/MainComponent.h
  src/gui/components/config/Attachments.cpp
  src/gui/components/config/Attachments.h
  src/gui/components/config/GraphComponent.h
  src/gui/components/config/InverterConfigComponent.cpp
  src/gui/components/config/InverterEditor.cpp
  src/gui/components/config/InverterEditor.h
  src/gui/components/config/MetadataEditor.cpp
  src/gui/components/config/MetadataEditor.h
  src/gui/components/config/TorqueMapComponent.cpp
  src/gui/components/config/TorqueMapComponent.h
  src/gui/windows/MainWindow.cpp
  src/gui/windows/MainWindow.h
Labels: bug, feature

#133 chore(trunk): bump to v1.0.1
  .trunk/trunk.yaml
Labels: chore

#135 build(windows): don't symlink compile commands to repo root on Windows
  CMakeLists.txt
Labels: build
