Repository sufst/vcu-gui, pull requests merged in 2022-11, with the labels that each got.

#136 chore(vscode): set up build/run/debug on Windows
  .vscode/c_cpp_properties.json
  .vscode/launch.json
Labels: build, chore

#139 fix(gui): add menu bar to main window on Linux and Windows
  src/Application.cpp
  src/Application.h
  src/gui/windows/MainWindow.cpp
Labels: bug

#142 feat(gui): add 'Help' menu to menu bar
  CMakeLists.txt
  src/CommandManager.h
  src/gui/menubar/MenuBar.cpp
  src/gui/menubar/MenuBar.h
Labels: bug, feature

#146 build(windows): fix C4244 int to float conversion warning
  src/gui/appearance/LookAndFeel.cpp
  src/gui/components/config/GraphComponent.h
  src/gui/windows/AboutWindow.cpp
Labels: build

#151 fix(gui): commit hash not shown in 'About' window on Windows
  CMakeLists.txt
Labels: bug
